// Generated by Wrangler. Run `pnpm wrangler:types` to regenerate.
// 注意：此处故意不 import cf-server/* 的具体类型，避免 tsc --noEmit
// 在主项目 strict 模式下走入 cf-server 源文件产生历史兼容错误。
// DurableObjectNamespace 的泛型参数在运行时通过 wrangler 绑定解析，
// 用 unknown/any 即可满足类型安全的开发需求。
interface Env {
	DB: D1Database;
	KV: KVNamespace;
	SECRET_KEY: string;
	ADMIN_USER: string;
	ADMIN_PASSWORD: string;
	SESSION_TTL: string;
	CAPTCHA_TTL: string;
	ROOM: DurableObjectNamespace<unknown>;
	MATCHMAKER: DurableObjectNamespace<unknown>;
}
